export const Musics = [
  
  {
    id: 0,
    name: 'Life Go On',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'BTS',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Life-Goes-On-BTS.mp3',
    thumb: 'imgMusic/life-goes-on.png',
    premium: 'premium',
    date: 'Hôm nay',
    timeTotal: '2400',
    timeString: '02:40',
    listening: 50,
  },
  {
    id: 1,
    name: 'Attention',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Attention',
    country: 'USA',
    type: 'US-UK',
    releaseDate: '2018',
    views: '1200500600',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/attention.png',
    premium: '',
    date: '2 ngày trước',
    timeTotal: '3600',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 2,
    name: 'Despacito',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Luis Fonte',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Despacito.mp3',
    thumb: 'imgMusic/despacito.png',
    premium: '',
    date: '3 ngày trước',
    timeTotal: '3260',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 3,
    name: 'DNA',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'BTS',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'DNA-BTS.mp3',
    thumb: 'imgMusic/dna.png',
    premium: '',
    date: 'Hôm qua',
    timeTotal: '4100',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 4,
    name: 'Hoa-Co-Lau-(TikTok-Speed-Up-Version)',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Phong Max',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Hoa-Co-Lau-(TikTok-Speed-Up-Version).mp3',
    thumb: 'imgMusic/hoa-co-lau.png',
    premium: '',
    date: '3 ngày trước',
    timeTotal: '2340',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 5,
    name: 'How You Like That',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Black Pink',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'How-You-Like-That-BLACKPINK.mp3',
    thumb: 'imgMusic/how-you-like-that.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '3100',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 6,
    name: 'Dreamers',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Jung Kook',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Dreamers-Jung-Kook.mp3',
    thumb: 'imgMusic/dreamers.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '3440',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 7,
    name: 'Some',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'BOLD4',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'some.mp3',
    thumb: 'imgMusic/some.png',
    premium: '',
    date: 'Hôm qua',
    timeTotal: '3500',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 8,
    name: 'Từ em mà ra',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Liz Z, Đức Anh',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'tu-em-ma-ra.mp3',
    thumb: 'imgMusic/some.png',
    premium: 'premium',
    date: '2 ngày trước',
    timeTotal: '2860',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 9,
    name: 'We don\'t talk anymore',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Charlie Puth',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'We-dont-talk-anymore-CharliePuth.mp3',
    thumb: 'imgMusic/we-dont-talk-anymore.jpg',
    premium: '',
    date: '1 ngày trước',
    timeTotal: '5200',
    timeString: '02:40',
    listening: 50,
  },   
  {
    id: 10,
    name: 'As If Its Your Last',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Black Pink',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'As-If-It-Your-Last-BLACKPINK.mp3',
    thumb: 'imgMusic/how-you-like-that.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '3680',
    timeString: '02:40',
    listening: 50,
  },  
  {
    id: 11,
    name: 'Life Go On',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'BTS',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Life-Goes-On-BTS.mp3',
    thumb: 'imgMusic/life-goes-on.png',
    premium: 'premium',
    date: 'Hôm nay',
    timeTotal: '2400',
    timeString: '02:40',
    listening: 50,
  },
  {
    id: 12,
    name: 'Attention',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Charlie Puth',
    country: 'USA',
    type: 'US-UK',
    releaseDate: '2018',
    views: '1200500600',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/attention.png',
    premium: '',
    date: '2 ngày trước',
    timeTotal: '3600',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 13,
    name: 'Despacito',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Luis Fonte',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Despacito.mp3',
    thumb: 'imgMusic/despacito.png',
    premium: '',
    date: '3 ngày trước',
    timeTotal: '3260',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 14,
    name: 'DNA',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'BTS',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'DNA-BTS.mp3',
    thumb: 'imgMusic/dna.png',
    premium: '',
    date: 'Hôm qua',
    timeTotal: '4100',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 15,
    name: 'Hoa-Co-Lau-(TikTok-Speed-Up-Version)',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Phong Max',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Hoa-Co-Lau-(TikTok-Speed-Up-Version).mp3',
    thumb: 'imgMusic/hoa-co-lau.png',
    premium: '',
    date: '3 ngày trước',
    timeTotal: '2340',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 16,
    name: 'How You Like That',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Black Pink',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'How-You-Like-That-BLACKPINK.mp3',
    thumb: 'imgMusic/how-you-like-that.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '3100',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 17,
    name: 'Dreamers',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Jung Kook',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Dreamers-Jung-Kook.mp3',
    thumb: 'imgMusic/dreamers.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '3440',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 18,
    name: 'Some',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'BOLD4',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'some.mp3',
    thumb: 'imgMusic/some.png',
    premium: '',
    date: 'Hôm qua',
    timeTotal: '3500',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 19,
    name: 'Từ em mà ra',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Liz Z, Đức Anh',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'tu-em-ma-ra.mp3',
    thumb: 'imgMusic/some.png',
    premium: 'premium',
    date: '2 ngày trước',
    timeTotal: '2860',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 20,
    name: 'We don\'t talk anymore',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Charlie Puth',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'We-dont-talk-anymore-CharliePuth.mp3',
    thumb: 'imgMusic/we-dont-talk-anymore.jpg',
    premium: '',
    date: '1 ngày trước',
    timeTotal: '5200',
    timeString: '02:40',
    listening: 50,
  },   
  {
    id: 21,
    name: 'As If Its Your Last',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Black Pink',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'As-If-It-Your-Last-BLACKPINK.mp3',
    thumb: 'imgMusic/how-you-like-that.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '3680',
    timeString: '02:40',
    listening: 50,
  },  
]

export const MusicsVN = [
  {
    id: 22,
    name: 'Chúng ta của hiện tại',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'BTS',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Life-Goes-On-BTS.mp3',
    thumb: 'imgMusic/life-goes-on.png',
    premium: 'premium',
    date: 'Hôm nay',
    timeTotal: '2400 ',
    timeString: '02:40',
    listening: 50,
  },
  {
    id: 23,
    name: 'See Tình',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Charlie Puth',
    country: 'USA',
    type: 'US-UK',
    releaseDate: '2018',
    views: '1200500600',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/attention.png',
    premium: '',
    date: '2 ngày trước',
    timeTotal: '2400 ',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 24,
    name: 'Hai phút hơn',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Luis Fonte',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Despacito.mp3',
    thumb: 'imgMusic/despacito.png',
    premium: '',
    date: '3 ngày trước',
    timeTotal: '2400 ',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 25,
    name: 'Bống bống bang bang',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'BTS',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'DNA-BTS.mp3',
    thumb: 'imgMusic/dna.png',
    premium: '',
    date: 'Hôm qua',
    timeTotal: '2400 ',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 26,
    name: 'Hoa-Co-Lau-(TikTok-Speed-Up-Version)',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Phong Max',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Hoa-Co-Lau-(TikTok-Speed-Up-Version).mp3',
    thumb: 'imgMusic/hoa-co-lau.png',
    premium: '',
    date: '3 ngày trước',
    timeTotal: '2400 ',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 27,
    name: 'Thương em',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Black Pink',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/how-you-like-that.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '2400 ',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 28,
    name: 'Chỉ là bạn',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Jung Kook',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/dreamers.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '2400 ',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 29,
    name: 'Ngày ấy bạn và tôi',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'BOLD4',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/some.png',
    premium: '',
    date: 'Hôm qua',
    timeTotal: '2400 ',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 30,
    name: 'Từ em mà ra',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Liz Z, Đức Anh',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/some.png',
    premium: 'premium',
    date: '2 ngày trước',
    timeTotal: '2400 ',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 31,
    name: 'Lạc trôi',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Charlie Puth',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/we-dont-talk-anymore.jpg',
    premium: '',
    date: '1 ngày trước',
    timeTotal: '2400 ',
    timeString: '02:40',
    listening: 50,
  }, 
  {
    id: 32,
    name: 'Anh đâu định khóc',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Charlie Puth',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/we-dont-talk-anymore.jpg',
    premium: '',
    date: '1 ngày trước',
    timeTotal: '2400 ',
    timeString: '02:40',
    listening: 50,
  },  
  {
    id: 33,
    name: 'Hơn cả yêu',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Black Pink',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/how-you-like-that.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '2400 ',
    timeString: '02:40',
    listening: 50,
  },   
]

export const MusicsWorld = [
  {
    id: 34,
    name: 'One Call Away',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'BTS',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Life-Goes-On-BTS.mp3',
    thumb: 'imgMusic/life-goes-on.png',
    premium: 'premium',
    date: 'Hôm nay',
    timeTotal: '2400 ',
    timeString: '02:40',
    listening: 50,
    
  },
  {
    id: 35,
    name: 'Made you look',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Charlie Puth',
    country: 'USA',
    type: 'US-UK',
    releaseDate: '2018',
    views: '1200500600',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/attention.png',
    premium: '',
    date: '2 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    id: 36,
    name: 'Baby',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Luis Fonte',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Despacito.mp3',
    thumb: 'imgMusic/despacito.png',
    premium: '',
    date: '3 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    id: 37,
    name: 'Play date',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'BTS',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'DNA-BTS.mp3',
    thumb: 'imgMusic/dna.png',
    premium: '',
    date: 'Hôm qua',
    timeTotal: '2400 ',
  }, 
  {
    id: 38,
    name: 'Shape of you',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Phong Max',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Hoa-Co-Lau-(TikTok-Speed-Up-Version).mp3',
    thumb: 'imgMusic/hoa-co-lau.png',
    premium: '',
    date: '3 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    id: 39,
    name: 'Girl like you',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Black Pink',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/how-you-like-that.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '2400 ',
  }, 
  {
    id: 40,
    name: 'Memories',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Jung Kook',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/dreamers.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '2400 ',
  }, 
  {
    id: 41,
    name: 'Ngày ấy bạn và tôi',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'BOLD4',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/some.png',
    premium: '',
    date: 'Hôm qua',
    timeTotal: '2400 ',
  }, 
  {
    id: 42,
    name: 'Senorita',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Liz Z, Đức Anh',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/some.png',
    premium: 'premium',
    date: '2 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    id: 43,
    name: 'Cupid',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Charlie Puth',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/we-dont-talk-anymore.jpg',
    premium: '',
    date: '1 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    id: 44,
    name: 'Sweet But Psycho',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Charlie Puth',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/we-dont-talk-anymore.jpg',
    premium: '',
    date: '1 ngày trước',
    timeTotal: '2400 ',
  },  
  {
    id: 45,
    name: 'Unstoppable',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Black Pink',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/how-you-like-that.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '2400 ',
  },   
]

export const MusicsKR = [
  {
    id: 46,
    name: 'Fake love',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'BTS',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Life-Goes-On-BTS.mp3',
    thumb: 'imgMusic/life-goes-on.png',
    premium: 'premium',
    date: 'Hôm nay',
    timeTotal: '2400 ',
  },
  {
    id: 47,
    name: 'Haru haru',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Charlie Puth',
    country: 'USA',
    type: 'US-UK',
    releaseDate: '2018',
    views: '1200500600',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/attention.png',
    premium: '',
    date: '2 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    id: 48,
    name: 'Flower',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Luis Fonte',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Despacito.mp3',
    thumb: 'imgMusic/despacito.png',
    premium: '',
    date: '3 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    id: 49,
    name: 'Pink venom',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'BTS',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'DNA-BTS.mp3',
    thumb: 'imgMusic/dna.png',
    premium: '',
    date: 'Hôm qua',
    timeTotal: '2400 ',
  }, 
  {
    id: 50,
    name: 'Kill this love',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Phong Max',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Hoa-Co-Lau-(TikTok-Speed-Up-Version).mp3',
    thumb: 'imgMusic/hoa-co-lau.png',
    premium: '',
    date: '3 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    id: 51,
    name: 'As if its your last',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Black Pink',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/how-you-like-that.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '2400 ',
  }, 
  {
    id: 52,
    name: 'Dynamite',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Jung Kook',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/dreamers.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '2400 ',
  }, 
  {
    id: 53,
    name: 'Bot with luv',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'BOLD4',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/some.png',
    premium: '',
    date: 'Hôm qua',
    timeTotal: '2400 ',
  }, 
  {
    id: 54,
    name: 'Life goes on',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Liz Z, Đức Anh',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/some.png',
    premium: 'premium',
    date: '2 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    id: 55,
    name: 'Ice cream',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Charlie Puth',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/we-dont-talk-anymore.jpg',
    premium: '',
    date: '1 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    id: 56,
    name: 'DDU-DU DDU-DU',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Charlie Puth',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/we-dont-talk-anymore.jpg',
    premium: '',
    date: '1 ngày trước',
    timeTotal: '2400 ',
  },  
  {
    id: 57,
    name: 'As If Its Your Last',
    album: 'Hẹn gặp lại anh (Single)',
    singer: 'Black Pink',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'As-If-It-Your-Last-BLACKPINK.mp3',
    thumb: 'imgMusic/how-you-like-that.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '2400 ',
  },   
]


export const Chills = [
  {
    title:'Chill',
    card: [
      {
        thumb: 'imgMain/img1.webp',
        desc: 'Khi bạn cần giai điệu để xoa dịu những tổn thương đã qua',
      },
      {
        thumb: 'imgMain/img2.webp',
        desc: 'Thả mình vào những giao điệu Lofi Chill nghe là nghiện',
      },

      {
        thumb: '/imgMain/img3.webp',
        desc: 'Thả mình vào những giai điệu V-Pop nhẹ nhàng',
      },
      {
        thumb: '/imgMain/img4.webp',
        desc: 'Ký ức ùa về cùng những giọng ca rất đỗi mộc mạc',
      },
      {
        thumb: '/imgMain/img5.webp',
        desc: 'Không ồn ào, không vội vàng, cùng thư giãn với âm nhạc Acoustic ngay tại đây',
      },
      
    ]
  },
  {
    title:'Một Chút Yêu Đời',
    card: [
      {
        thumb: '/imgMain/img6.webp',
        desc: 'Ưng quá chừng với giai điệu V-Pop làm bạn vui tươi cả ngày',
      },
      {
        thumb: '/imgMain/img7.webp',
        desc: 'Nhẹ nhàng chữa lành trái tim bằng giai điệu tích cực',
      },
      {
        thumb: '/imgMain/img8.webp',
        desc: 'Cứ vui lên vì những âu lo rồi cũng sẽ qua thôi',
      },
      {
        thumb: '/imgMain/img9.webp',
        desc: 'Yêu là phải nói, giống như đói là phải ăn',
      },
      {
        thumb: '/imgMain/img10.webp',
        desc: 'Nhạc gì mà nghe xong dính cứng ngắc',
      },
    ]
  },
  {
    title:'Remix Là Dance Luôn',
    card: [
      {
        thumb: '/imgMain/img-dance-1.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
      {
        thumb: '/imgMain/img-dance-2.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
      {
        thumb: '/imgMain/img-dance-3.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
      {
        thumb: '/imgMain/img-dance-4.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
      {
        thumb: '/imgMain/img-dance-5.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
    ]
  },
  {
    title:'Tâm Trạng Tan Chậm',
    card: [
      {
        thumb: '/imgMain/img11.webp',
        desc: 'Nếu nỗi nhớ là một bông hoa thì sẽ là đóa hoa không màu, vì chẳng có màu nào tô',
      },
      {
        thumb: '/imgMain/img12.webp',
        desc: 'Hát có thể làm vơi đi bớt nỗi lòng, nhưng liệu có khỏa lấp được vỡ nát trong tim?',
      },
      {
        thumb: '/imgMain/img13.webp',
        desc: 'Dù rằng đã hết lòng mà tình vẫn hóa hư không',
      },
      {
        thumb: '/imgMain/img14.webp',
        desc: 'Những khúc tình buồn ngày xưa qua tiếng hát ngày nay',
      },
      {
        thumb: '/imgMain/img15.webp',
        desc: 'Để những giai điệu nhẹ nhàng dìu bạn bước qua nỗi cô đơn',
      },
    ]
  },
  {
    title:'Nghệ Sĩ Thịnh Hành',
    card: [
      {
        thumb: '/imgMain/img16.webp',
        desc: 'Em Là Ai và những Hit khác của Keyo',  
      },
      {
        thumb: '/imgMain/img17.webp',
        desc: 'Tình cũ và những bản Hit gây thương nhớ của Khải Đăng',  
      },
      {
        thumb: '/imgMain/img18.webp',
        desc: 'Khi Thành Đạt kể chuyện tình buồn bằng âm nhạc',  
      },
      {
        thumb: '/imgMain/img19.webp',
        desc: 'Cùng Châu Khải Phong viết ngôn tình cùng các Hit nổi bật nhất',  
      },
      {
        thumb: '/imgMain/img20.webp',
        desc: 'Thuận theo ý trời, nghe nhạc Đông Nhi',  
      },
    ]
  },
]

export const Top100 = [
  {
    title:'Nổi Bật',
    card: [
      {
        thumb: 'imgMain/img1.webp',
        desc: 'Top 100 Bài Hát Nhạc Trẻ Hay Nhất',
      },
      {
        thumb: 'imgMain/img2.webp',
        desc: 'Top 100 Pop Âu Mỹ Hay Nhất',
      },

      {
        thumb: 'imgMain/img3.webp',
        desc: 'Top 100 Nhạc Hàn QUốc Hay Nhất',
      },
      {
        thumb: 'imgMain/img4.webp',
        desc: 'Top 100 Nhạc Rap Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Nhạc Electronic/Dance Âu Mỹ Hay Nhất',
      },
      
    ]
  },
  {
    title:'Nhạc Việt Nam',
    card: [
      {
        thumb: 'imgMain/img1.webp',
        desc: 'Top 100 Nhạc EDM Việt Hay Nhất',
      },
      {
        thumb: 'imgMain/img2.webp',
        desc: 'Top 100 Nhạc V-Pop Hay Nhất',
      },

      {
        thumb: 'imgMain/img3.webp',
        desc: 'Top 100 Nhạc Phim Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img4.webp',
        desc: 'Top 100 Nhạc Trịnh Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Cải Lương Hay Nhất',
      },
      {
        thumb: 'imgMain/img1.webp',
        desc: 'Top 100 Nhạc Không Lời Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img2.webp',
        desc: 'Top 100 Nhạc Thiếu Nhi Hay Nhất',
      },

      {
        thumb: 'imgMain/img3.webp',
        desc: 'Top 100 Nhạc Quê Hương Hay Nhất',
      },
      {
        thumb: 'imgMain/img4.webp',
        desc: 'Top 100 Nhạc Cách Mạng Việt Nam',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Nhạc Dance Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Nhạc Rap Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Nhạc Rock Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Nhạc Trữ Tình Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Bài Hát Nhạc Trẻ Hay Nhất',
      },
      
    ]
  },
  {
    title:'Nhạc Châu Á',
    card: [
      {
        thumb: 'imgMain/img6.webp',
        desc: 'Top 100 Nhạc Phim Hoa Ngữ Hay Nhất',
      },
      {
        thumb: 'imgMain/img7.webp',
        desc: 'Top 100 Nhạc Phim Hàn Quốc Hay Nhất',
      },
      {
        thumb: 'imgMain/img8.webp',
        desc: 'Top 100 Nhạc Hoa Hay Nhất',
      },
      {
        thumb: 'imgMain/img9.webp',
        desc: 'Top 100 Nhạc Nhật Bản Hay Nhất',
      },
      {
        thumb: 'imgMain/img10.webp',
        desc: 'Top 100 Nhạc Hàn Quốc Hay Nhất',
      },
    ]
  },
  {
    title:'Nhạc Âu Mỹ ',
    card: [
      {
        thumb: 'imgMain/img-dance-1.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
      {
        thumb: 'imgMain/img-dance-2.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
      {
        thumb: 'imgMain/img-dance-3.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
      {
        thumb: 'imgMain/img-dance-4.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
      {
        thumb: 'imgMain/img-dance-5.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
    ]
  },
]



export const Haha = [
  {
    title:'Nhạc Việt Nam',
    card: [
      {
        thumb: 'imgMain/img1.webp',
        desc: 'Top 100 Nhạc EDM Việt Hay Nhất',
      },
      {
        thumb: 'imgMain/img2.webp',
        desc: 'Top 100 Nhạc V-Pop Hay Nhất',
      },

      {
        thumb: 'imgMain/img3.webp',
        desc: 'Top 100 Nhạc Phim Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img4.webp',
        desc: 'Top 100 Nhạc Trịnh Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Cải Lương Hay Nhất',
      },
      {
        thumb: 'imgMain/img1.webp',
        desc: 'Top 100 Nhạc Không Lời Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img2.webp',
        desc: 'Top 100 Nhạc Thiếu Nhi Hay Nhất',
      },

      {
        thumb: 'imgMain/img3.webp',
        desc: 'Top 100 Nhạc Quê Hương Hay Nhất',
      },
      {
        thumb: 'imgMain/img4.webp',
        desc: 'Top 100 Nhạc Cách Mạng Việt Nam',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Nhạc Dance Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Nhạc Rap Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Nhạc Rock Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Nhạc Trữ Tình Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Bài Hát Nhạc Trẻ Hay Nhất',
      },
      
    ]
  },
]