export const Musics = [
  {
    name: 'Life Go On',
    singer: 'BTS',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Life-Goes-On-BTS.mp3',
    thumb: 'imgMusic/life-goes-on.png',
    premium: 'premium',
    date: 'Hôm nay',
    timeTotal: '240 ',
  },
  {
    name: 'Attention',
    singer: 'Charlie Puth',
    country: 'USA',
    type: 'US-UK',
    releaseDate: '2018',
    views: '1200500600',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/attention.png',
    premium: '',
    date: '2 ngày trước',
    timeTotal: '360 ',
  }, 
  {
    name: 'Despacito',
    singer: 'Luis Fonte',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Despacito.mp3',
    thumb: 'imgMusic/despacito.png',
    premium: '',
    date: '3 ngày trước',
    timeTotal: '326 ',
  }, 
  {
    name: 'DNA',
    singer: 'BTS',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'DNA-BTS.mp3',
    thumb: 'imgMusic/dna.png',
    premium: '',
    date: 'Hôm qua',
    timeTotal: ' 410',
  }, 
  {
    name: 'Hoa-Co-Lau-(TikTok-Speed-Up-Version)',
    singer: 'Phong Max',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Hoa-Co-Lau-(TikTok-Speed-Up-Version).mp3',
    thumb: 'imgMusic/hoa-co-lau.png',
    premium: '',
    date: '3 ngày trước',
    timeTotal: '234 ',
  }, 
  {
    name: 'How You Like That',
    singer: 'Black Pink',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/how-you-like-that.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '310',
  }, 
  {
    name: 'Dreamers',
    singer: 'Jung Kook',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/dreamers.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '344',
  }, 
  {
    name: 'Some',
    singer: 'BOLD4',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/some.png',
    premium: '',
    date: 'Hôm qua',
    timeTotal: '3500',
  }, 
  {
    name: 'Từ em mà ra',
    singer: 'Liz Z, Đức Anh',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/some.png',
    premium: 'premium',
    date: '2 ngày trước',
    timeTotal: '286',
  }, 
  {
    name: 'We don\'t talk anymore',
    singer: 'Charlie Puth',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/we-dont-talk-anymore.jpg',
    premium: '',
    date: '1 ngày trước',
    timeTotal: '520',
  },   
  {
    name: 'How You Like That',
    singer: 'Black Pink',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/how-you-like-that.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '368',
  },   
]

export const MusicsVN = [
  {
    name: 'Chúng ta của hiện tại',
    singer: 'BTS',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Life-Goes-On-BTS.mp3',
    thumb: 'imgMusic/life-goes-on.png',
    premium: 'premium',
    date: 'Hôm nay',
    timeTotal: '2400 ',
  },
  {
    name: 'See Tình',
    singer: 'Charlie Puth',
    country: 'USA',
    type: 'US-UK',
    releaseDate: '2018',
    views: '1200500600',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/attention.png',
    premium: '',
    date: '2 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Hai phút hơn',
    singer: 'Luis Fonte',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Despacito.mp3',
    thumb: 'imgMusic/despacito.png',
    premium: '',
    date: '3 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Bống bống bang bang',
    singer: 'BTS',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'DNA-BTS.mp3',
    thumb: 'imgMusic/dna.png',
    premium: '',
    date: 'Hôm qua',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Hoa-Co-Lau-(TikTok-Speed-Up-Version)',
    singer: 'Phong Max',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Hoa-Co-Lau-(TikTok-Speed-Up-Version).mp3',
    thumb: 'imgMusic/hoa-co-lau.png',
    premium: '',
    date: '3 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Thương em',
    singer: 'Black Pink',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/how-you-like-that.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Chỉ là bạn',
    singer: 'Jung Kook',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/dreamers.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Ngày ấy bạn và tôi',
    singer: 'BOLD4',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/some.png',
    premium: '',
    date: 'Hôm qua',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Từ em mà ra',
    singer: 'Liz Z, Đức Anh',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/some.png',
    premium: 'premium',
    date: '2 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Lạc trôi',
    singer: 'Charlie Puth',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/we-dont-talk-anymore.jpg',
    premium: '',
    date: '1 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Anh đâu định khóc',
    singer: 'Charlie Puth',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/we-dont-talk-anymore.jpg',
    premium: '',
    date: '1 ngày trước',
    timeTotal: '2400 ',
  },  
  {
    name: 'Hơn cả yêu',
    singer: 'Black Pink',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/how-you-like-that.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '2400 ',
  },   
]

export const MusicsWorld = [
  {
    name: 'One Call Away',
    singer: 'BTS',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Life-Goes-On-BTS.mp3',
    thumb: 'imgMusic/life-goes-on.png',
    premium: 'premium',
    date: 'Hôm nay',
    timeTotal: '2400 ',
  
  },
  {
    name: 'Made you look',
    singer: 'Charlie Puth',
    country: 'USA',
    type: 'US-UK',
    releaseDate: '2018',
    views: '1200500600',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/attention.png',
    premium: '',
    date: '2 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Baby',
    singer: 'Luis Fonte',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Despacito.mp3',
    thumb: 'imgMusic/despacito.png',
    premium: '',
    date: '3 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Play date',
    singer: 'BTS',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'DNA-BTS.mp3',
    thumb: 'imgMusic/dna.png',
    premium: '',
    date: 'Hôm qua',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Shape of you',
    singer: 'Phong Max',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Hoa-Co-Lau-(TikTok-Speed-Up-Version).mp3',
    thumb: 'imgMusic/hoa-co-lau.png',
    premium: '',
    date: '3 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Girl like you',
    singer: 'Black Pink',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/how-you-like-that.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Memories',
    singer: 'Jung Kook',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/dreamers.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Ngày ấy bạn và tôi',
    singer: 'BOLD4',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/some.png',
    premium: '',
    date: 'Hôm qua',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Senorita',
    singer: 'Liz Z, Đức Anh',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/some.png',
    premium: 'premium',
    date: '2 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Cupid',
    singer: 'Charlie Puth',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/we-dont-talk-anymore.jpg',
    premium: '',
    date: '1 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Sweet But Psycho',
    singer: 'Charlie Puth',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/we-dont-talk-anymore.jpg',
    premium: '',
    date: '1 ngày trước',
    timeTotal: '2400 ',
  },  
  {
    name: 'Unstoppable',
    singer: 'Black Pink',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/how-you-like-that.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '2400 ',
  },   
]

export const MusicsKR = [
  {
    name: 'Fake love',
    singer: 'BTS',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Life-Goes-On-BTS.mp3',
    thumb: 'imgMusic/life-goes-on.png',
    premium: 'premium',
    date: 'Hôm nay',
    timeTotal: '2400 ',
  },
  {
    name: 'Haru haru',
    singer: 'Charlie Puth',
    country: 'USA',
    type: 'US-UK',
    releaseDate: '2018',
    views: '1200500600',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/attention.png',
    premium: '',
    date: '2 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Flower',
    singer: 'Luis Fonte',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Despacito.mp3',
    thumb: 'imgMusic/despacito.png',
    premium: '',
    date: '3 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Pink venom',
    singer: 'BTS',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'DNA-BTS.mp3',
    thumb: 'imgMusic/dna.png',
    premium: '',
    date: 'Hôm qua',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Kill this love',
    singer: 'Phong Max',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Hoa-Co-Lau-(TikTok-Speed-Up-Version).mp3',
    thumb: 'imgMusic/hoa-co-lau.png',
    premium: '',
    date: '3 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    name: 'As if its your last',
    singer: 'Black Pink',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/how-you-like-that.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Dynamite',
    singer: 'Jung Kook',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/dreamers.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Bot with luv',
    singer: 'BOLD4',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/some.png',
    premium: '',
    date: 'Hôm qua',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Life goes on',
    singer: 'Liz Z, Đức Anh',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/some.png',
    premium: 'premium',
    date: '2 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    name: 'Ice cream',
    singer: 'Charlie Puth',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/we-dont-talk-anymore.jpg',
    premium: '',
    date: '1 ngày trước',
    timeTotal: '2400 ',
  }, 
  {
    name: 'DDU-DU DDU-DU',
    singer: 'Charlie Puth',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/we-dont-talk-anymore.jpg',
    premium: '',
    date: '1 ngày trước',
    timeTotal: '2400 ',
  },  
  {
    name: 'How You Like That',
    singer: 'Black Pink',
    country: 'Korean',
    type: 'K-pop',
    releaseDate: '2020',
    views: '1200000000',
    path: 'Attention-Charlie-Puth.mp3',
    thumb: 'imgMusic/how-you-like-that.png',
    premium: '',
    date: 'Hôm nay',
    timeTotal: '2400 ',
  },   
]


export const Chills = [
  {
    title:'Chill',
    card: [
      {
        thumb: 'imgMain/img1.webp',
        desc: 'Khi bạn cần giai điệu để xoa dịu những tổn thương đã qua',
      },
      {
        thumb: 'imgMain/img2.webp',
        desc: 'Thả mình vào những giao điệu Lofi Chill nghe là nghiện',
      },

      {
        thumb: 'imgMain/img3.webp',
        desc: 'Thả mình vào những giai điệu V-Pop nhẹ nhàng',
      },
      {
        thumb: 'imgMain/img4.webp',
        desc: 'Ký ức ùa về cùng những giọng ca rất đỗi mộc mạc',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Không ồn ào, không vội vàng, cùng thư giãn với âm nhạc Acoustic ngay tại đây',
      },
      
    ]
  },
  {
    title:'Một Chút Yêu Đời',
    card: [
      {
        thumb: '/imgMain/img6.webp',
        desc: 'Ưng quá chừng với giai điệu V-Pop làm bạn vui tươi cả ngày',
      },
      {
        thumb: '/imgMain/img7.webp',
        desc: 'Nhẹ nhàng chữa lành trái tim bằng giai điệu tích cực',
      },
      {
        thumb: '/imgMain/img8.webp',
        desc: 'Cứ vui lên vì những âu lo rồi cũng sẽ qua thôi',
      },
      {
        thumb: '/imgMain/img9.webp',
        desc: 'Yêu là phải nói, giống như đói là phải ăn',
      },
      {
        thumb: '/imgMain/img10.webp',
        desc: 'Nhạc gì mà nghe xong dính cứng ngắc',
      },
    ]
  },
  {
    title:'Remix Là Dance Luôn',
    card: [
      {
        thumb: '/imgMain/img-dance-1.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
      {
        thumb: '/imgMain/img-dance-2.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
      {
        thumb: '/imgMain/img-dance-3.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
      {
        thumb: '/imgMain/img-dance-4.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
      {
        thumb: '/imgMain/img-dance-5.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
    ]
  },
  {
    title:'Tâm Trạng Tan Chậm',
    card: [
      {
        thumb: '/imgMain/img11.webp',
        desc: 'Nếu nỗi nhớ là một bông hoa thì sẽ là đóa hoa không màu, vì chẳng có màu nào tô',
      },
      {
        thumb: '/imgMain/img12.webp',
        desc: 'Hát có thể làm vơi đi bớt nỗi lòng, nhưng liệu có khỏa lấp được vỡ nát trong tim?',
      },
      {
        thumb: '/imgMain/img13.webp',
        desc: 'Dù rằng đã hết lòng mà tình vẫn hóa hư không',
      },
      {
        thumb: '/imgMain/img14.webp',
        desc: 'Những khúc tình buồn ngày xưa qua tiếng hát ngày nay',
      },
      {
        thumb: '/imgMain/img15.webp',
        desc: 'Để những giai điệu nhẹ nhàng dìu bạn bước qua nỗi cô đơn',
      },
    ]
  },
  {
    title:'Nghệ Sĩ Thịnh Hành',
    card: [
      {
        thumb: '/imgMain/img16.webp',
        desc: 'Em Là Ai và những Hit khác của Keyo',  
      },
      {
        thumb: '/imgMain/img17.webp',
        desc: 'Tình cũ và những bản Hit gây thương nhớ của Khải Đăng',  
      },
      {
        thumb: '/imgMain/img18.webp',
        desc: 'Khi Thành Đạt kể chuyện tình buồn bằng âm nhạc',  
      },
      {
        thumb: '/imgMain/img19.webp',
        desc: 'Cùng Châu Khải Phong viết ngôn tình cùng các Hit nổi bật nhất',  
      },
      {
        thumb: '/imgMain/img20.webp',
        desc: 'Thuận theo ý trời, nghe nhạc Đông Nhi',  
      },
    ]
  },
]

export const Top100 = [
  {
    title:'Nổi Bật',
    card: [
      {
        thumb: 'imgMain/img1.webp',
        desc: 'Top 100 Bài Hát Nhạc Trẻ Hay Nhất',
      },
      {
        thumb: 'imgMain/img2.webp',
        desc: 'Top 100 Pop Âu Mỹ Hay Nhất',
      },

      {
        thumb: 'imgMain/img3.webp',
        desc: 'Top 100 Nhạc Hàn QUốc Hay Nhất',
      },
      {
        thumb: 'imgMain/img4.webp',
        desc: 'Top 100 Nhạc Rap Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Nhạc Electronic/Dance Âu Mỹ Hay Nhất',
      },
      
    ]
  },
  {
    title:'Nhạc Việt Nam',
    card: [
      {
        thumb: 'imgMain/img1.webp',
        desc: 'Top 100 Nhạc EDM Việt Hay Nhất',
      },
      {
        thumb: 'imgMain/img2.webp',
        desc: 'Top 100 Nhạc V-Pop Hay Nhất',
      },

      {
        thumb: 'imgMain/img3.webp',
        desc: 'Top 100 Nhạc Phim Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img4.webp',
        desc: 'Top 100 Nhạc Trịnh Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Cải Lương Hay Nhất',
      },
      {
        thumb: 'imgMain/img1.webp',
        desc: 'Top 100 Nhạc Không Lời Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img2.webp',
        desc: 'Top 100 Nhạc Thiếu Nhi Hay Nhất',
      },

      {
        thumb: 'imgMain/img3.webp',
        desc: 'Top 100 Nhạc Quê Hương Hay Nhất',
      },
      {
        thumb: 'imgMain/img4.webp',
        desc: 'Top 100 Nhạc Cách Mạng Việt Nam',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Nhạc Dance Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Nhạc Rap Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Nhạc Rock Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Nhạc Trữ Tình Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Bài Hát Nhạc Trẻ Hay Nhất',
      },
      
    ]
  },
  {
    title:'Nhạc Châu Á',
    card: [
      {
        thumb: 'imgMain/img6.webp',
        desc: 'Top 100 Nhạc Phim Hoa Ngữ Hay Nhất',
      },
      {
        thumb: 'imgMain/img7.webp',
        desc: 'Top 100 Nhạc Phim Hàn Quốc Hay Nhất',
      },
      {
        thumb: 'imgMain/img8.webp',
        desc: 'Top 100 Nhạc Hoa Hay Nhất',
      },
      {
        thumb: 'imgMain/img9.webp',
        desc: 'Top 100 Nhạc Nhật Bản Hay Nhất',
      },
      {
        thumb: 'imgMain/img10.webp',
        desc: 'Top 100 Nhạc Hàn Quốc Hay Nhất',
      },
    ]
  },
  {
    title:'Nhạc Âu Mỹ ',
    card: [
      {
        thumb: 'imgMain/img-dance-1.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
      {
        thumb: 'imgMain/img-dance-2.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
      {
        thumb: 'imgMain/img-dance-3.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
      {
        thumb: 'imgMain/img-dance-4.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
      {
        thumb: 'imgMain/img-dance-5.webp',
        desc: 'Nhạc Việt "lâu phai" và gây nghiện hoài hoài', 
      },
    ]
  },
]



export const Haha = [
  {
    title:'Nhạc Việt Nam',
    card: [
      {
        thumb: 'imgMain/img1.webp',
        desc: 'Top 100 Nhạc EDM Việt Hay Nhất',
      },
      {
        thumb: 'imgMain/img2.webp',
        desc: 'Top 100 Nhạc V-Pop Hay Nhất',
      },

      {
        thumb: 'imgMain/img3.webp',
        desc: 'Top 100 Nhạc Phim Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img4.webp',
        desc: 'Top 100 Nhạc Trịnh Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Cải Lương Hay Nhất',
      },
      {
        thumb: 'imgMain/img1.webp',
        desc: 'Top 100 Nhạc Không Lời Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img2.webp',
        desc: 'Top 100 Nhạc Thiếu Nhi Hay Nhất',
      },

      {
        thumb: 'imgMain/img3.webp',
        desc: 'Top 100 Nhạc Quê Hương Hay Nhất',
      },
      {
        thumb: 'imgMain/img4.webp',
        desc: 'Top 100 Nhạc Cách Mạng Việt Nam',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Nhạc Dance Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Nhạc Rap Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Nhạc Rock Việt Nam Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Nhạc Trữ Tình Hay Nhất',
      },
      {
        thumb: 'imgMain/img5.webp',
        desc: 'Top 100 Bài Hát Nhạc Trẻ Hay Nhất',
      },
      
    ]
  },
]